//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Pulsar", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Pulsar.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Pulsar-test.ck boilerplate ChucK program
//      to help test your chugin (see Pulsar-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../include/Pulsar.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR( pulsar_ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( pulsar_dtor );

// example of getter/setter
CK_DLL_MFUN( pulsar_setFreq );
CK_DLL_MFUN( pulsar_getFreq );
CK_DLL_MFUN( pulsar_setRate );
CK_DLL_MFUN( pulsar_getRate );
CK_DLL_MFUN( pulsar_setRandomRate );
CK_DLL_MFUN( pulsar_getRandomRate );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( pulsar_tick );

// this is a special offset reserved for chugin internal data
t_CKINT pulsar_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Pulsar )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "v1.0.0" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "Everett M. Carpenter" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "A simple granulating sine or cosine wave." );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Pulsar )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "Pulsar" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "Pulsar", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, pulsar_ctor );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, pulsar_dtor );

    // for UGens only: add tick function
    // NOTE a non-UGen class should remove or comment out this next line
    QUERY->add_ugen_func( QUERY, pulsar_tick, NULL, 1, 1 );
    // NOTE: if this is to be a UGen with more than 1 channel,
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // example of adding setter method
    QUERY->add_mfun( QUERY, pulsar_setFreq, "float", "freq" );
    // example of adding argument to the above method
    QUERY->add_arg( QUERY, "float", "frequency" );
    QUERY->doc_func( QUERY, "Set oscillator's frequency." );

    // example of adding getter method
    QUERY->add_mfun( QUERY, pulsar_getFreq, "float", "freq" );
    QUERY->doc_func( QUERY, "Get oscillator's frequency." );

    QUERY->add_mfun(QUERY, pulsar_setRate, "void", "size");
    QUERY->add_arg(QUERY, "float", "size");
    QUERY->doc_func(QUERY, "Set grain size in ms.");

    QUERY->add_mfun(QUERY, pulsar_getRate, "float", "size");
    QUERY->doc_func(QUERY, "Get grain size in ms.");

    QUERY->add_mfun(QUERY, pulsar_setRandomRate, "void", "randomSize");
    QUERY->add_arg(QUERY, "float", "randomness");
    QUERY->doc_func(QUERY, "Set randomness of grain size. (Additive, this is a random number between 0 and 'randomSize' which is added to the base grain size)");

    QUERY->add_mfun(QUERY, pulsar_getRandomRate, "float", "randomSize");
    QUERY->doc_func(QUERY, "Get randomness of grain size.");
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    pulsar_data_offset = QUERY->add_mvar( QUERY, "int", "@p_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( pulsar_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, pulsar_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    Pulsar * p_obj = new Pulsar( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, pulsar_data_offset ) = (t_CKINT)p_obj;
}


// implementation for the destructor
CK_DLL_DTOR( pulsar_dtor )
{
    // get our c++ class pointer
    Pulsar * p_obj = (Pulsar *)OBJ_MEMBER_INT( SELF, pulsar_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( p_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, pulsar_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( pulsar_tick )
{
    // get our c++ class pointer
    Pulsar * p_obj = (Pulsar *)OBJ_MEMBER_INT(SELF, pulsar_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if( p_obj ) *out = p_obj->tick();

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN( pulsar_setFreq )
{
    // get our c++ class pointer
    Pulsar * p_obj = (Pulsar *)OBJ_MEMBER_INT( SELF, pulsar_data_offset );

    // get next argument
    // NOTE argument type must match what is specified above in CK_DLL_QUERY
    // NOTE this advances the ARGS pointer, so save in variable for re-use
    t_CKFLOAT freq = GET_NEXT_FLOAT( ARGS );
    
    // call setParam() and set the return value
    if( p_obj ) p_obj->setFrequency( freq );
}


// example implementation for getter
CK_DLL_MFUN( pulsar_getFreq )
{
    // get our c++ class pointer
    Pulsar * p_obj = (Pulsar *)OBJ_MEMBER_INT( SELF, pulsar_data_offset );

    // call getParam() and set the return value
    if( p_obj ) RETURN->v_float = p_obj->getFrequency();
}

// set rate
CK_DLL_MFUN( pulsar_setRate )
{
    // get arg
    t_CKFLOAT nrate = GET_NEXT_FLOAT( ARGS );
    // get our grain
    Pulsar* p_obj = (Pulsar* )OBJ_MEMBER_INT( SELF, pulsar_data_offset );
    // call function
    if( p_obj ) p_obj->setRate( nrate );
}

// get rate
CK_DLL_MFUN( pulsar_getRate )
{
    // get grain
    Pulsar* p_obj = (Pulsar* )OBJ_MEMBER_INT( SELF, pulsar_data_offset );

    if( p_obj ) RETURN->v_float = p_obj->getRate();
    else RETURN->v_float = -1.0;
}

// set random
CK_DLL_MFUN( pulsar_setRandomRate )
{
    // get arg
    t_CKFLOAT randomness = GET_NEXT_FLOAT( ARGS );
    // get grain
    Pulsar* p_obj = (Pulsar* )OBJ_MEMBER_INT( SELF, pulsar_data_offset );

    if( p_obj ) p_obj->setRandomRate( randomness );
}

CK_DLL_MFUN( pulsar_getRandomRate )
{
    // get grain
    Pulsar* p_obj = (Pulsar* )OBJ_MEMBER_INT( SELF, pulsar_data_offset );

    if( p_obj ) RETURN->v_float = p_obj->getRandomRate();
    else RETURN->v_float = -1.0;
}
