//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Grain.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Grain.chug Grain-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Grain.chug Grain-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

GameController controller( 0 );

Pulsar testL[8] => Gain volL( 1.0 / 8.0 ) => dac.chan( 0 );
Pulsar testR[8] => Gain volR( 1.0 / 8.0 ) => dac.chan( 1 );

fun void randomizePitch( Pulsar pl[] )
{
    for( int i; i < pl.size(); i++ ) { pl[i].freq( Math.randomf() * 1425.0 ); }
}

fun void randomizeSize( Pulsar pl[] )
{
    for( int i; i < pl.size(); i++ ) { ( Math.fabs( controller.joysticks[1] ) * 2000.0 ) + 0.01 => pl[i].randomSize; }
}

fun void randomizeOneSize( Pulsar pl[] )
{
    ( Math.fabs( controller.joysticks[1] ) * 2000.0 ) + 0.01 => float randomValue;
    for( int i; i < pl.size(); i++ ) { randomValue => pl[i].randomSize; }
}

fun void setSize( Pulsar pl[], float size )
{
    for( int i; i < pl.size(); i++ ) { size => pl[i].size; }
}

while( true )
{
    if( controller.buttonState[6] ) me.exit();
	else if( controller.buttonState[7] ) randomizePitch( testL );
	else if( controller.buttonState[8] ) randomizePitch( testR );
    // size
    setSize( testL, ( Math.fabs( controller.joysticks[0] ) * 450.0 ) + 5.0 );
    setSize( testR, ( Math.fabs( controller.joysticks[2] ) * 450.0 ) + 5.0 );
    randomizeSize( testL ); randomizeSize( testR );
    10::ms => now;
}
