//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Grain", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Grain.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Grain-test.ck boilerplate ChucK program
//      to help test your chugin (see Grain-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../include/FileGrain.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR( grain_ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( grain_dtor );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( grain_tick );

CK_DLL_MFUN( grain_setGrainSize );
CK_DLL_MFUN( grain_getGrainSize );
CK_DLL_MFUN( grain_setRandomGrainSize );
CK_DLL_MFUN( grain_getRandomGrainSize );

CK_DLL_MFUN( grain_setPitch );
CK_DLL_MFUN( grain_getPitch );
CK_DLL_MFUN( grain_setRandomPitch );
CK_DLL_MFUN( grain_getRandomPitch );

CK_DLL_MFUN( grain_setPosition );
CK_DLL_MFUN( grain_getPosition );
CK_DLL_MFUN( grain_setRandomPosition );
CK_DLL_MFUN( grain_getRandomPosition );

CK_DLL_MFUN( grain_openFile );
CK_DLL_MFUN( grain_closeFile );
CK_DLL_MFUN( grain_fileSize );

// this is a special offset reserved for chugin internal data
t_CKINT grain_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Grain )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "v1.0.0" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "Everett M. Carpenter" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "A single granulator with typical parameters." );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "carpee2 [at] rpi [dot] edu" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Grain )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "Grain" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "Grain", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, grain_ctor );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, grain_dtor );

    // for UGens only: add tick function
    // NOTE a non-UGen class should remove or comment out this next line
    QUERY->add_ugen_func( QUERY, grain_tick, NULL, 0, 1 );
    // NOTE: if this is to be a UGen with more than 1 channel,
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    QUERY->add_mfun( QUERY, grain_setGrainSize, "void", "size" );
    QUERY->add_arg( QUERY, "float", "size" );
    QUERY->doc_func( QUERY, "Set grain size in ms." );

    QUERY->add_mfun( QUERY, grain_getGrainSize, "float", "size" );
    QUERY->doc_func( QUERY, "Get grain size in ms." );

    QUERY->add_mfun( QUERY, grain_setRandomGrainSize, "void", "randomSize" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of grain size. (Additive, this is a random number between 0 and 'randomSize' which is added to the base grain size)" );

    QUERY->add_mfun( QUERY, grain_getRandomGrainSize, "float", "randomSize" );
    QUERY->doc_func( QUERY, "Get randomness of grain size." );

    QUERY->add_mfun( QUERY, grain_setPitch, "void", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->doc_func( QUERY, "Set pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, grain_getPitch, "float", "pitch" );
    QUERY->doc_func( QUERY, "Get the pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, grain_setRandomPitch, "void", "randomPitch" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of pitch." );

    QUERY->add_mfun( QUERY, grain_getRandomPitch, "float", "randomPitch" );
    QUERY->doc_func( QUERY, "Get randomness of pitch." );

    QUERY->add_mfun( QUERY, grain_setPosition, "void", "position" );
    QUERY->add_arg( QUERY, "float", "position" );
    QUERY->doc_func( QUERY, "Set position of granulator in file." );

    QUERY->add_mfun( QUERY, grain_getPosition, "float", "position" );
    QUERY->doc_func( QUERY, "Get position of granulator." );

    QUERY->add_mfun( QUERY, grain_setRandomPosition, "void", "randomPosition" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of position." );

    QUERY->add_mfun( QUERY, grain_getRandomPosition, "float", "randomPosition" );
    QUERY->doc_func( QUERY, "Get randomness of position." );

    QUERY->add_mfun( QUERY, grain_openFile, "void", "openFile" );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->doc_func( QUERY, "Open file at the given path." );

    QUERY->add_mfun( QUERY, grain_closeFile, "void", "closeFile" );
    QUERY->doc_func( QUERY, "Close the active file." );

    QUERY->add_mfun( QUERY, grain_fileSize, "float", "fileSize" );
    QUERY->doc_func( QUERY, "Retrieve file size in samples." );

    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    grain_data_offset = QUERY->add_mvar( QUERY, "int", "@g_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( grain_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, grain_data_offset ) = 0;

    // instantiate our internal c++ class representation
    FileGrain* g_obj = new FileGrain( API->vm->srate( VM ) );

    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, grain_data_offset ) = ( t_CKINT )g_obj;
}


// implementation for the destructor
CK_DLL_DTOR( grain_dtor )
{
    // get our c++ class pointer
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( g_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, grain_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( grain_tick )
{
    // get our c++ class pointer
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    // invoke our tick function; store in the magical out variable
    if ( g_obj ) *out = g_obj->tick();

    // yes
    return TRUE;
}

// set rate
CK_DLL_MFUN( grain_setGrainSize )
{
    // get arg
    t_CKFLOAT nrate = GET_NEXT_FLOAT( ARGS );
    // get our grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // call function
    if( g_obj ) g_obj->setGrainSize( nrate );
}

// get rate
CK_DLL_MFUN( grain_getGrainSize )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) RETURN->v_float = g_obj->getGrainSize();
    else RETURN->v_float = -1.0;
}

// set random
CK_DLL_MFUN( grain_setRandomGrainSize )
{
    // get arg
    t_CKFLOAT randomness = GET_NEXT_FLOAT( ARGS );
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) g_obj->setRandomGrainSize( randomness );
}

CK_DLL_MFUN( grain_getRandomGrainSize )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) RETURN->v_float = g_obj->getRandomGrainSize();
    else RETURN->v_float = -1.0;
}


CK_DLL_MFUN( grain_setPitch )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // get arg
    t_CKFLOAT pitch = GET_NEXT_FLOAT( ARGS );
    // set
    if( g_obj ) g_obj->setPitch( pitch );
}

CK_DLL_MFUN( grain_getPitch )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // retrieve
    if( g_obj ) RETURN->v_float = g_obj->getPitch();
}

// set random
CK_DLL_MFUN( grain_setRandomPitch )
{
    // get arg
    t_CKFLOAT randomness = GET_NEXT_FLOAT( ARGS );
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) g_obj->setRandomPitch( randomness );
}

CK_DLL_MFUN( grain_getRandomPitch )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) RETURN->v_float = g_obj->getRandomPitch();
    else RETURN->v_float = -1.0;
}

CK_DLL_MFUN( grain_setPosition )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // get arg
    t_CKFLOAT pitch = GET_NEXT_FLOAT( ARGS );
    // set
    if( g_obj ) g_obj->samp->setPosition( pitch );
}

CK_DLL_MFUN( grain_getPosition )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // retrieve
    if( g_obj ) RETURN->v_float = g_obj->samp->getPosition() / g_obj->samp->getFileSize();
}

// set random
CK_DLL_MFUN( grain_setRandomPosition )
{
    // get arg
    t_CKFLOAT randomness = GET_NEXT_FLOAT( ARGS );
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) g_obj->setRandomPosition( randomness );
}

CK_DLL_MFUN( grain_getRandomPosition )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) RETURN->v_float = g_obj->getRandomPosition();
    else RETURN->v_float = -1.0;
}

CK_DLL_MFUN( grain_openFile )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    // get file
    Chuck_String* path = GET_NEXT_STRING( ARGS );

    if( g_obj ) g_obj->openFile( API->object->str( path ) );
}

CK_DLL_MFUN( grain_closeFile )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );
    
    if( g_obj ) g_obj->samp->closeFile();
}

CK_DLL_MFUN( grain_fileSize )
{
    // get grain
    FileGrain* g_obj = ( FileGrain* )OBJ_MEMBER_INT( SELF, grain_data_offset );

    if( g_obj ) RETURN->v_int = g_obj->samp->getFileSize();
    else RETURN->v_int = -1;
}