//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Assemblage", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Assemblage.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Assemblage-test.ck boilerplate ChucK program
//      to help test your chugin (see Assemblage-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../../include/Assemblage.h"

// general includes
#include <iostream>

// declaration of chugin constructor
CK_DLL_CTOR( assemblage_ctor );
CK_DLL_CTOR( assemblage_2ctor );
CK_DLL_CTOR( assemblage_3ctor );
CK_DLL_CTOR( assemblage_4ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( assemblage_dtor );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( assemblage_tick );

CK_DLL_MFUN( assemblage_setGrainSize );
CK_DLL_MFUN( assemblage_set2GrainSize );
CK_DLL_MFUN( assemblage_setRandomGrainSize );
CK_DLL_MFUN( assemblage_set2RandomGrainSize );

CK_DLL_MFUN( assemblage_setPitch );
CK_DLL_MFUN( assemblage_set2Pitch );
CK_DLL_MFUN( assemblage_setRandomPitch );
CK_DLL_MFUN( assemblage_set2RandomPitch );

CK_DLL_MFUN( assemblage_setPosition );
CK_DLL_MFUN( assemblage_set2Position );
CK_DLL_MFUN( assemblage_setRandomPosition );
CK_DLL_MFUN( assemblage_set2RandomPosition );


CK_DLL_MFUN( assemblage_getGrainSize );
CK_DLL_MFUN( assemblage_getRandomGrainSize );

CK_DLL_MFUN( assemblage_getPitch );
CK_DLL_MFUN( assemblage_getRandomPitch );

CK_DLL_MFUN( assemblage_getPosition );
CK_DLL_MFUN( assemblage_getRandomPosition );

CK_DLL_MFUN( assemblage_count );
CK_DLL_MFUN( assemblage_openFile );
CK_DLL_MFUN( assemblage_closeFile );

CK_DLL_MFUN( assemblage_samples );

// this is a special offset reserved for chugin internal data
t_CKINT assemblage_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Assemblage )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Assemblage )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "Assemblage" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "Assemblage", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, assemblage_ctor );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`
    QUERY->add_ctor( QUERY, assemblage_2ctor );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->add_arg( QUERY, "int", "num" );

    QUERY->add_ctor( QUERY, assemblage_3ctor );
    QUERY->add_arg( QUERY, "string", "file" );

    QUERY->add_ctor( QUERY, assemblage_4ctor );
    QUERY->add_arg( QUERY, "int", "number" );

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, assemblage_dtor );

    // for UGens only: add tick function
    // NOTE a non-UGen class should remove or comment out this next line
    QUERY->add_ugen_func( QUERY, assemblage_tick, NULL, 0, 1 );
    // NOTE: if this is to be a UGen with more than 1 channel,
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_setGrainSize, "void", "size" );
    QUERY->add_arg( QUERY, "float", "size" );
    QUERY->doc_func( QUERY, "Set assemblage size in ms." );

    QUERY->add_mfun( QUERY, assemblage_setRandomGrainSize, "void", "randomSize" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of assemblage size. (Additive, this is a random number between 0 and 'randomSize' which is added to the base assemblage size)" );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_setPitch, "void", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->doc_func( QUERY, "Set pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, assemblage_setRandomPitch, "void", "randomPitch" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of pitch." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_setPosition, "void", "position" );
    QUERY->add_arg( QUERY, "float", "position" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );

    QUERY->add_mfun( QUERY, assemblage_setPosition, "void", "position" );
    QUERY->add_arg( QUERY, "int", "position" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );

    QUERY->add_mfun( QUERY, assemblage_setRandomPosition, "void", "randomPosition" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of position." );

    // ===========================================================================================

    QUERY->add_mfun(QUERY, assemblage_set2GrainSize, "void", "size");
    QUERY->add_arg(QUERY, "float[]", "size");
    QUERY->doc_func(QUERY, "Set assemblage size in ms.");

    QUERY->add_mfun( QUERY, assemblage_set2RandomGrainSize, "void", "randomSize" );
    QUERY->add_arg( QUERY, "float[]", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of assemblage size. (Additive, this is a random number between 0 and 'randomSize' which is added to the base assemblage size)" );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_set2Pitch, "void", "pitch" );
    QUERY->add_arg( QUERY, "float[]", "pitch" );
    QUERY->doc_func( QUERY, "Set pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, assemblage_set2RandomPitch, "void", "randomPitch" );
    QUERY->add_arg( QUERY, "float[]", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of pitch." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_set2Position, "void", "position" );
    QUERY->add_arg( QUERY, "float[]", "position" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );

    QUERY->add_mfun( QUERY, assemblage_set2RandomPosition, "void", "randomPosition" );
    QUERY->add_arg( QUERY, "float[]", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of position." );

    // ===========================================================================================
    /*
    QUERY->add_mfun( QUERY, assemblage_getGrainSize, "float[]", "size" );
    QUERY->doc_func( QUERY, "Get assemblage size in ms." );

    QUERY->add_mfun( QUERY, assemblage_getRandomGrainSize, "float[]", "randomSize" );
    QUERY->doc_func( QUERY, "Get randomness of assemblage size." );

    QUERY->add_mfun( QUERY, assemblage_getPitch, "float[]", "pitch" );
    QUERY->doc_func( QUERY, "Get the pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, assemblage_getRandomPitch, "float[]", "randomPitch" );
    QUERY->doc_func( QUERY, "Get randomness of pitch." );

    QUERY->add_mfun( QUERY, assemblage_getPosition, "float[]", "position" );
    QUERY->doc_func( QUERY, "Get position of assemblage." );

    QUERY->add_mfun( QUERY, assemblage_getRandomPosition, "float[]", "randomPosition" );
    QUERY->doc_func( QUERY, "Get randomness of position." );
    */
    // ===========================================================================================

    QUERY->add_mfun( QUERY, assemblage_count, "int", "count" );
    QUERY->doc_func( QUERY, "How many pieces." );

    QUERY->add_mfun( QUERY, assemblage_openFile, "void", "openFile" );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->doc_func( QUERY, "Open file at the given path." );

    QUERY->add_mfun( QUERY, assemblage_closeFile, "void", "closeFile" );
    QUERY->doc_func( QUERY, "Close the active file." );

    QUERY->add_mfun( QUERY, assemblage_samples, "int", "samples" );
    QUERY->doc_func( QUERY, "Return how many samples are in the active file." );

    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    assemblage_data_offset = QUERY->add_mvar( QUERY, "int", "@g_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( assemblage_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( assemblage_2ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = 0;
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );
    t_CKINT num_grains = GET_NEXT_INT( ARGS );
    if( num_grains <= 0 ) num_grains = 4;

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM), num_grains );
    a_obj->openFile( API->object->str( path ) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( assemblage_3ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = 0;
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM) );
    a_obj->openFile( API->object->str( path ) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( assemblage_4ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = 0;
   
    t_CKINT num_grains = GET_NEXT_INT( ARGS );
    if( num_grains <= 0 ) num_grains = 4;

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM), num_grains );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = (t_CKINT)a_obj;
}


// implementation for the destructor
CK_DLL_DTOR( assemblage_dtor )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT( SELF, assemblage_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( a_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, assemblage_data_offset ) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( assemblage_tick )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if( a_obj ) *out = a_obj->tick();

    // yes
    return TRUE;
}

CK_DLL_MFUN( assemblage_setGrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT size = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setSize( size );
}

CK_DLL_MFUN( assemblage_set2GrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* sizes = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setSize( sizes, API );
}

CK_DLL_MFUN( assemblage_setPitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT pitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setPitch( pitch );
}

CK_DLL_MFUN( assemblage_set2Pitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* pitches = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPitch( pitches, API );
}

CK_DLL_MFUN( assemblage_setPosition )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT pos = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setSize( pos );
}

CK_DLL_MFUN( assemblage_set2Position )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* positions = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPosition( positions, API );
}

CK_DLL_MFUN( assemblage_setRandomGrainSize ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT randomSize = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomSize( randomSize );
}

CK_DLL_MFUN( assemblage_set2RandomGrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* randomgrainSizes = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomSize( randomgrainSizes, API );
}

CK_DLL_MFUN( assemblage_setRandomPitch ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT randomPitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomPitch( randomPitch );
}

CK_DLL_MFUN( assemblage_set2RandomPitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* randompitches = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomPitch( randompitches, API );
}

CK_DLL_MFUN( assemblage_setRandomPosition ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    t_CKFLOAT randomPitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomPosition( randomPitch );
}

CK_DLL_MFUN( assemblage_set2RandomPosition )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);

    Chuck_ArrayFloat* radnompositions = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomPosition( radnompositions, API );
}

CK_DLL_MFUN( assemblage_openFile )
{
    // get granulator
    Assemblage* g_obj = (Assemblage* )OBJ_MEMBER_INT(SELF, assemblage_data_offset);
    // get file
    Chuck_String* path = GET_NEXT_STRING( ARGS );

    if( g_obj ) g_obj->openFile( API->object->str( path ) );
}

CK_DLL_MFUN( assemblage_closeFile )
{
    // get granulator
    Assemblage* g_obj = (Assemblage* )OBJ_MEMBER_INT(SELF, assemblage_data_offset);
    
    if( g_obj ) g_obj->closeFile();
}

CK_DLL_MFUN( assemblage_samples )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);
    
    if( a_obj ) RETURN->v_int = a_obj->samples();
    else RETURN->v_int = -1;
}

CK_DLL_MFUN( assemblage_count )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, assemblage_data_offset);
    
    if( a_obj ) RETURN->v_int = a_obj->count();
    else RETURN->v_int = -1;
}

