//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "LPC", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (LPC.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a LPC-test.ck boilerplate ChucK program
//      to help test your chugin (see LPC-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR( lpc_ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( lpc_dtor );

// example of getter/setter
CK_DLL_MFUN( lpc_setParam );
CK_DLL_MFUN( lpc_getParam );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( lpc_tick );

// this is a special offset reserved for chugin internal data
t_CKINT lpc_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( LPC )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( LPC )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "LPC" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "LPC", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, lpc_ctor );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, lpc_dtor );

    // for UGens only: add tick function
    // NOTE a non-UGen class should remove or comment out this next line
    QUERY->add_ugen_func( QUERY, lpc_tick, NULL, 1, 1 );
    // NOTE: if this is to be a UGen with more than 1 channel,
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // example of adding setter method
    QUERY->add_mfun( QUERY, lpc_setParam, "float", "param" );
    // example of adding argument to the above method
    QUERY->add_arg( QUERY, "float", "arg" );

    // example of adding getter method
    QUERY->add_mfun( QUERY, lpc_getParam, "float", "param" );
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    lpc_data_offset = QUERY->add_mvar( QUERY, "int", "@lpc_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( lpc_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, lpc_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    LPC * lpc_obj = new LPC( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, lpc_data_offset ) = (t_CKINT)lpc_obj;
}


// implementation for the destructor
CK_DLL_DTOR( lpc_dtor )
{
    // get our c++ class pointer
    LPC * lpc_obj = (LPC *)OBJ_MEMBER_INT( SELF, lpc_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( lpc_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, lpc_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( lpc_tick )
{
    // get our c++ class pointer
    LPC * lpc_obj = (LPC *)OBJ_MEMBER_INT(SELF, lpc_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if( lpc_obj ) *out = lpc_obj->tick( in );

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN( lpc_setParam )
{
    // get our c++ class pointer
    LPC * lpc_obj = (LPC *)OBJ_MEMBER_INT( SELF, lpc_data_offset );

    // get next argument
    // NOTE argument type must match what is specified above in CK_DLL_QUERY
    // NOTE this advances the ARGS pointer, so save in variable for re-use
    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    
    // call setParam() and set the return value
    RETURN->v_float = lpc_obj->setParam( arg1 );
}


// example implementation for getter
CK_DLL_MFUN(lpc_getParam)
{
    // get our c++ class pointer
    LPC * lpc_obj = (LPC *)OBJ_MEMBER_INT( SELF, lpc_data_offset );

    // call getParam() and set the return value
    RETURN->v_float = lpc_obj->getParam();
}
