//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "SoundFile", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (SoundFile.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a SoundFile-test.ck boilerplate ChucK program
//      to help test your chugin (see SoundFile-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../../include/SoundFile.h"

// general includes
#include <iostream>

// declaration of chugin constructor
CK_DLL_CTOR( soundfile_ctor );
CK_DLL_CTOR( soundfile_2ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( soundfile_dtor );

// example of getter/setter
CK_DLL_MFUN( soundfile_getSize );
CK_DLL_MFUN( soundfile_getRate );
CK_DLL_MFUN( soundfile_openFile );

// this is a special offset reserved for chugin internal data
t_CKINT soundfile_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( SoundFile )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "emc" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "A wrapper for the Synthesis Toolkit's StkFrames class to be used in ChucK." );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( SoundFile )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "SoundFile" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "SoundFile", "Object" );

    // register default constructor
    QUERY->add_ctor( QUERY, soundfile_ctor );

    QUERY->add_ctor( QUERY, soundfile_2ctor );
    QUERY->add_arg( QUERY, "string", "file" );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, soundfile_dtor );

    QUERY->add_mfun( QUERY, soundfile_getRate, "int", "rate" );

    QUERY->add_mfun( QUERY, soundfile_getSize, "int", "size" );

    QUERY->add_mfun( QUERY, soundfile_openFile, "void", "open" );
    QUERY->add_arg( QUERY, "string", "file" );

    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    soundfile_data_offset = QUERY->add_mvar( QUERY, "int", "@sf_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( soundfile_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, soundfile_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    SoundFile * sf_obj = new SoundFile( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, soundfile_data_offset ) = (t_CKINT)sf_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( soundfile_2ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, soundfile_data_offset ) = 0;
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );
    API->object->str( path );

    // instantiate our internal c++ class representation
    SoundFile * sf_obj = new SoundFile( API->vm->srate(VM) );
    if( sf_obj ) sf_obj->openFile( API->object->str( path ) );

	std::cout << "Size: " << sf_obj->fileSize() << std::endl;
	
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, soundfile_data_offset ) = (t_CKINT)sf_obj;
}


// implementation for the destructor
CK_DLL_DTOR( soundfile_dtor )
{
    // get our c++ class pointer
    SoundFile * sf_obj = (SoundFile *)OBJ_MEMBER_INT( SELF, soundfile_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( sf_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, soundfile_data_offset ) = 0;
}

// example implementation for setter
CK_DLL_MFUN( soundfile_getRate )
{
    // get our c++ class pointer
    SoundFile * sf_obj = (SoundFile *)OBJ_MEMBER_INT( SELF, soundfile_data_offset );
    
    // call setParam() and set the return value
    RETURN->v_float = sf_obj->fileRate();
}

// example implementation for setter
CK_DLL_MFUN( soundfile_getSize )
{
    // get our c++ class pointer
    SoundFile * sf_obj = (SoundFile *)OBJ_MEMBER_INT( SELF, soundfile_data_offset );
    
    // call setParam() and set the return value
    RETURN->v_float = sf_obj->fileSize();
}

// example implementation for setter
CK_DLL_MFUN( soundfile_openFile )
{
    // get our c++ class pointer
    SoundFile * sf_obj = (SoundFile *)OBJ_MEMBER_INT( SELF, soundfile_data_offset );
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );
    API->object->str( path );
    if( sf_obj ) sf_obj->openFile( API->object->str( path ) );
}
