//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Assemblage", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Assemblage.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Assemblage-test.ck boilerplate ChucK program
//      to help test your chugin (see Assemblage-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../../include/Assemblage.h"
#include "../../include/SoundFile.h"
// #include "../../SoundFile.chug/src/SoundFile.cpp"

// general includes
#include <iostream>

// declaration of chugin constructor
CK_DLL_CTOR( collage_ctor );
CK_DLL_CTOR( collage_2ctor );
CK_DLL_CTOR( collage_3ctor );
CK_DLL_CTOR( collage_4ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( collage_dtor );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( collage_tick );

CK_DLL_MFUN( collage_setGrainSize );
CK_DLL_MFUN( collage_set2GrainSize );
CK_DLL_MFUN( collage_setRandomGrainSize );
CK_DLL_MFUN( collage_set2RandomGrainSize );

CK_DLL_MFUN( collage_setPitch );
CK_DLL_MFUN( collage_set2Pitch );
CK_DLL_MFUN( collage_set3Pitch );
CK_DLL_MFUN( collage_set4Pitch );

CK_DLL_MFUN( collage_setRandomPitch );
CK_DLL_MFUN( collage_set2RandomPitch );

CK_DLL_MFUN( collage_setPosition );
CK_DLL_MFUN( collage_set2Position );
CK_DLL_MFUN( collage_set3Position );
CK_DLL_MFUN( collage_set4Position );
CK_DLL_MFUN( collage_setRandomPosition );
CK_DLL_MFUN( collage_set2RandomPosition );

CK_DLL_MFUN( collage_getGrainSize );
CK_DLL_MFUN( collage_getRandomGrainSize );

CK_DLL_MFUN( collage_getPitch );
CK_DLL_MFUN( collage_getTargetPitch );
CK_DLL_MFUN( collage_getRandomPitch );

CK_DLL_MFUN( collage_getPosition );
CK_DLL_MFUN( collage_getTargetPosition );
CK_DLL_MFUN( collage_getRandomPosition );

CK_DLL_MFUN( collage_count );
CK_DLL_MFUN( collage_openFile );
CK_DLL_MFUN( collage_closeFile );
CK_DLL_MFUN( collage_openExternalFile );

CK_DLL_MFUN( collage_samples );
CK_DLL_MFUN( collage_duration );

CK_DLL_MFUN( collage_setSpace );
CK_DLL_MFUN( collage_set2Space );
CK_DLL_MFUN( collage_getSpace );
CK_DLL_MFUN( collage_setRandomSpace );
CK_DLL_MFUN( collage_getRandomSpace );

CK_DLL_MFUN( collage_sync );
// this is a special offset reserved for chugin internal data
t_CKINT collage_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Collage )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "Everett M. Carpenter" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Collage )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "Collage" );

    QUERY->begin_class( QUERY, "Collage", "UGen" );

    QUERY->add_ctor( QUERY, collage_ctor );

    QUERY->add_ctor( QUERY, collage_2ctor );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->add_arg( QUERY, "int", "num" );

    QUERY->add_ctor( QUERY, collage_3ctor );
    QUERY->add_arg( QUERY, "string", "file" );

    QUERY->add_ctor( QUERY, collage_4ctor );
    QUERY->add_arg( QUERY, "int", "number" );

    QUERY->add_dtor( QUERY, collage_dtor );

    QUERY->add_ugen_func( QUERY, collage_tick, NULL, 0, 1 );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_setGrainSize, "void", "size" );
    QUERY->add_arg( QUERY, "float", "size" );
    QUERY->doc_func( QUERY, "Set assemblage size in ms." );

    QUERY->add_mfun( QUERY, collage_setRandomGrainSize, "void", "randomSize" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of assemblage size. (Additive, this is a random number between 0 and 'randomSize' which is added to the base assemblage size)" );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_setPitch, "void", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->doc_func( QUERY, "Set pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, collage_setRandomPitch, "void", "randomPitch" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of pitch." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_setPosition, "void", "position" );
    QUERY->add_arg( QUERY, "float", "position" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );

    /*
    QUERY->add_mfun( QUERY, collage_setPosition, "void", "position" );
    QUERY->add_arg( QUERY, "int", "position" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );
    */

    QUERY->add_mfun( QUERY, collage_setRandomPosition, "void", "randomPosition" );
    QUERY->add_arg( QUERY, "float", "randomness" );
    QUERY->doc_func( QUERY, "Set randomness of position." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_set3Pitch, "void", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->add_arg( QUERY, "dur", "interpolation" );
    QUERY->doc_func( QUERY, "Set pitch/rate of internal file." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_set3Position, "void", "position" );
    QUERY->add_arg( QUERY, "float", "position" );
    QUERY->add_arg( QUERY, "dur", "interpolation" );
    QUERY->doc_func( QUERY, "Set position of assemblage in file." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_getGrainSize, "float", "size" );
    QUERY->doc_func( QUERY, "Get assemblage size in ms." );

    QUERY->add_mfun( QUERY, collage_getRandomGrainSize, "float", "randomSize" );
    QUERY->doc_func( QUERY, "Get randomness of assemblage size." );

    QUERY->add_mfun( QUERY, collage_getPitch, "float", "pitch" );
    QUERY->doc_func( QUERY, "Get the pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, collage_getTargetPitch, "float", "targetPitch" );
    QUERY->doc_func( QUERY, "Get the target pitch/rate of internal file." );

    QUERY->add_mfun( QUERY, collage_getRandomPitch, "float", "randomPitch" );
    QUERY->doc_func( QUERY, "Get randomness of pitch." );

    QUERY->add_mfun( QUERY, collage_getPosition, "float", "position" );
    QUERY->doc_func( QUERY, "Get position of assemblage." );

    QUERY->add_mfun( QUERY, collage_getTargetPosition, "float", "targetPosition" );
    QUERY->doc_func( QUERY, "Get target position of assemblage." );

    QUERY->add_mfun( QUERY, collage_getRandomPosition, "float", "randomPosition" );
    QUERY->doc_func( QUERY, "Get randomness of position." );

    // ===========================================================================================

    QUERY->add_mfun( QUERY, collage_count, "int", "count" );
    QUERY->doc_func( QUERY, "How many pieces." );

    QUERY->add_mfun( QUERY, collage_sync, "void", "sync" );
    QUERY->doc_func( QUERY, "Have all grains complete their current cycle, and once they're all done, they start all together." );

    QUERY->add_mfun( QUERY, collage_openFile, "void", "openFile" );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->doc_func( QUERY, "Open file at the given path." );

    QUERY->add_mfun( QUERY, collage_openExternalFile, "void", "openFile" );
    QUERY->add_arg( QUERY, "Object", "file" );
    QUERY->doc_func( QUERY, "Utilize provided audio buffer." );

    QUERY->add_mfun( QUERY, collage_closeFile, "void", "closeFile" );
    QUERY->doc_func( QUERY, "Close the active file." );

    QUERY->add_mfun( QUERY, collage_samples, "int", "samples" );
    QUERY->doc_func( QUERY, "Return how many samples are in the active file." );

    QUERY->add_mfun( QUERY, collage_duration, "dur", "duration" );
    QUERY->doc_func( QUERY, "Length of file as a ChucK duration." );

    QUERY->add_mfun( QUERY, collage_setSpace, "void", "spacer" );
    QUERY->add_arg( QUERY, "dur", "time" );

    QUERY->add_mfun( QUERY, collage_getSpace, "dur", "spacer" );
    QUERY->doc_func( QUERY, "Get size of space" );

    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    collage_data_offset = QUERY->add_mvar( QUERY, "int", "@g_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( collage_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( collage_2ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = 0;
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );
    t_CKINT num_grains = GET_NEXT_INT( ARGS );
    if( num_grains <= 0 ) num_grains = 4;

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM), num_grains );
    a_obj->openFile( API->object->str( path ) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( collage_3ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = 0;
    
    Chuck_String* path =  GET_NEXT_STRING( ARGS );

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM) );
    a_obj->openFile( API->object->str( path ) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = (t_CKINT)a_obj;
}

// implementation for the default constructor
CK_DLL_CTOR( collage_4ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = 0;
   
    t_CKINT num_grains = GET_NEXT_INT( ARGS );
    if( num_grains <= 0 ) num_grains = 4;

    // instantiate our internal c++ class representation
    Assemblage * a_obj = new Assemblage( API->vm->srate(VM), num_grains );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = (t_CKINT)a_obj;
}


// implementation for the destructor
CK_DLL_DTOR( collage_dtor )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT( SELF, collage_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( a_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, collage_data_offset ) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( collage_tick )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if( a_obj ) *out = a_obj->tick();

    // yes
    return TRUE;
}

CK_DLL_MFUN( collage_setGrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT size = GET_NEXT_FLOAT( ARGS );

    if( a_obj ) a_obj->setSize( size );
}

CK_DLL_MFUN( collage_set2GrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* sizes = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setSize( sizes, API );
}

CK_DLL_MFUN( collage_setPitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT pitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setPitch( pitch );
}

CK_DLL_MFUN( collage_set2Pitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* pitches = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPitch( pitches, API );
}

CK_DLL_MFUN( collage_set3Pitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT pitch = GET_NEXT_FLOAT( ARGS );
    t_CKDUR time_to = GET_NEXT_DUR( ARGS );
    
    double srate_khz = ( ( double )API->vm->srate( VM ) / 1000.0 ); 

    if( a_obj ) a_obj->setPitch( pitch, ( time_to ) / srate_khz );
}

CK_DLL_MFUN( collage_set4Pitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* pitches = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    Chuck_ArrayFloat* times_to = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPitch( pitches, times_to, VM, API );
}

CK_DLL_MFUN( collage_setPosition )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT pos = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setPosition( pos );
}

CK_DLL_MFUN( collage_set2Position )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* positions = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPosition( positions, API );
}

CK_DLL_MFUN( collage_set3Position )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT pos = GET_NEXT_FLOAT( ARGS );
    t_CKDUR time_to = GET_NEXT_DUR( ARGS );

    double srate_khz = ( ( double )API->vm->srate( VM ) / 1000.0 ); 
    
    if( a_obj ) a_obj->setPosition( pos, ( time_to ) / srate_khz );
}

CK_DLL_MFUN( collage_set4Position )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* positions = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    Chuck_ArrayFloat* times_to = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setPosition( positions, times_to, VM, API );
}

CK_DLL_MFUN( collage_setRandomGrainSize ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT randomSize = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomSize( randomSize );
}

CK_DLL_MFUN( collage_set2RandomGrainSize )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* randomgrainSizes = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomSize( randomgrainSizes, API );
}

CK_DLL_MFUN( collage_setRandomPitch ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT randomPitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomPitch( randomPitch );
}

CK_DLL_MFUN( collage_set2RandomPitch )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* randompitches = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomPitch( randompitches, API );
}

CK_DLL_MFUN( collage_setRandomPosition ) // need to implement this on the Assemblage side
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    t_CKFLOAT randomPitch = GET_NEXT_FLOAT( ARGS );
    
    if( a_obj ) a_obj->setRandomPosition( randomPitch );
}

CK_DLL_MFUN( collage_set2RandomPosition )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);

    Chuck_ArrayFloat* radnompositions = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );
    
    if( a_obj ) a_obj->setRandomPosition( radnompositions, API );
}

CK_DLL_MFUN( collage_openFile )
{
    // get granulator
    Assemblage* g_obj = (Assemblage* )OBJ_MEMBER_INT(SELF, collage_data_offset);
    // get file
    Chuck_String* path = GET_NEXT_STRING( ARGS );

    if( g_obj ) g_obj->openFile( API->object->str( path ) );
}

CK_DLL_MFUN( collage_openExternalFile )
{
    // get granulator
    Assemblage* g_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);

    // get file
    SoundFile* myBuffer = (SoundFile*)GET_NEXT_OBJECT( ARGS );
	std::cout << "Assemblage receiving file size: " << myBuffer->fileSize() << std::endl;
    // if( g_obj && myBuffer ) g_obj->linkBuffer( (stk::StkFrames*)myBuffer->buffer() );
}

CK_DLL_MFUN( collage_closeFile )
{
    // get granulator
    Assemblage* g_obj = (Assemblage* )OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( g_obj ) g_obj->closeFile();
}

CK_DLL_MFUN( collage_samples )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_int = a_obj->samples();
    else RETURN->v_int = -1;
}

CK_DLL_MFUN( collage_duration )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_dur = a_obj->samples();
    else RETURN->v_dur = 0;
}

CK_DLL_MFUN( collage_sync )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) a_obj->sync();
}

CK_DLL_MFUN( collage_count )
{
    // get our c++ class pointer
    Assemblage * a_obj = (Assemblage *)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_int = a_obj->count();
    else RETURN->v_int = -1;
}

CK_DLL_MFUN( collage_setSpace )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    t_CKDUR space_time = GET_NEXT_DUR( ARGS );
    if( a_obj ) a_obj->setGap( (unsigned int)space_time );
}

CK_DLL_MFUN( collage_set2Space )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
 
    Chuck_ArrayFloat* space_time = (Chuck_ArrayFloat*)GET_NEXT_OBJECT( ARGS );

    if( a_obj ) a_obj->setGap( space_time, API );
}

CK_DLL_MFUN( collage_getSpace )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_dur = a_obj->getGap();
}

CK_DLL_MFUN( collage_setRandomSpace )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    t_CKDUR space_time = GET_NEXT_DUR( ARGS );
    if( a_obj ) a_obj->setRandomGap( (unsigned int)space_time );
}

CK_DLL_MFUN( collage_getRandomSpace )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    // if( a_obj ) RETURN->v_dur = a_obj->getRandomGap();
}

CK_DLL_MFUN( collage_getGrainSize )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBaseSize();
}

CK_DLL_MFUN( collage_getRandomGrainSize )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBaseRandomSize();
}

CK_DLL_MFUN( collage_getPitch )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBasePitch();
}

CK_DLL_MFUN( collage_getTargetPitch )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getTargetPitch();
}

CK_DLL_MFUN( collage_getRandomPitch )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBaseRandomPitch();
}

CK_DLL_MFUN( collage_getPosition )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBasePosition();
}

CK_DLL_MFUN( collage_getTargetPosition )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getTargetPosition();
}

CK_DLL_MFUN( collage_getRandomPosition )
{
    // get our c++ class pointer
    Assemblage* a_obj = (Assemblage*)OBJ_MEMBER_INT(SELF, collage_data_offset);
    
    if( a_obj ) RETURN->v_float = a_obj->getBaseRandomPosition();
}
