//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Grain.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Grain.chug Grain-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Grain.chug Grain-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

GameController controller( 0 );
0 => controller.print;

Grain testL => Gain volL( 0.8 ) => dac.chan( 0 );
Grain testR => Gain volR( 0.8 ) => dac.chan( 1 );

"../include/randomvaporwave.WAV" => string filename;
testL.openFile( filename );
testR.openFile( filename );

while( true )
{
    if( controller.buttonState[6] ) me.exit();
    // size
    ( controller.joysticks[0] * 245.0 ) + 5.0 => float size;
    size => testL.size; 
    size => testR.size;
    ( Math.fabs( controller.joysticks[1] ) * testL.size() * 2000000000000000000000.0 ) + 0.01 => float position;
    position => testL.position;
    position => testR.position;

    // size right
    ( controller.joysticks[2] * 85.0 ) + 5.0 => float randomPosition;
    randomPosition => testL.randomPosition;
    randomPosition => testR.randomPosition;
    ( Math.fabs( controller.joysticks[3] ) * testR.size() * 2.0 ) + 0.01 => float randomPitch;
    randomPitch => testL.randomPitch;
    randomPitch => testR.randomPitch;

    <<< testL.size(), testL.position(), testL.randomPosition(), testL.randomPitch(), testL.pitch() >>>;
    5::ms => now;
}