//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Grain.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Grain.chug Grain-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Grain.chug Grain-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

GameController controller( 0 );

16 => int N;

Grain testL[N] => Gain volL( 1.0 / N ) => NRev revL( 0.125 ) => dac.chan( 0 );
Grain testR[N] => Gain volR( 1.0 / N ) => NRev revR( 0.125 ) => dac.chan( 1 );

fun void randomizePitch( Grain pl[], float factor )
{
    for( int i; i < pl.size(); i++ ) { pl[i].pitch( Math.randomf() * factor ); }
}

fun void randomizeSize( Grain pl[] )
{
    for( int i; i < pl.size(); i++ ) { ( Math.fabs( controller.joysticks[1] ) * 200.0 ) + 0.01 => pl[i].randomSize; }
}

fun void randomizeOneSize( Grain pl[] )
{
    ( Math.fabs( controller.joysticks[1] ) * 200.0 ) + 0.01 => float randomValue;
    for( int i; i < pl.size(); i++ ) { randomValue => pl[i].randomSize; }
}

fun void randomizeOneSize( Grain pl[], float value )
{
    for( int i; i < pl.size(); i++ ) { value => pl[i].randomSize; }
}

fun void setSize( Grain pl[], float size )
{
    for( int i; i < pl.size(); i++ ) { Math.random2f( 0.0, size / 2.0 ) + size => pl[i].size; }
}

fun void setPitch( Grain pl[], float pitch )
{
    for( int i; i < pl.size(); i++ ) { pitch => pl[i].pitch; }
}

for( int i; i < N; i++ )
{
    testL[i].openFile( "../include/blackpaint.wav" );
    testR[i].openFile( "../include/blackpaint.wav" );
}

while( true )
{
    if( controller.buttonState[6] ) me.exit();
	if( controller.buttonState[7] ) randomizePitch( testL, 0.25 );
	if( controller.buttonState[8] ) randomizePitch( testR, 0.25 );
    if( controller.hatState[3] ) { randomizePitch( testL, 4.0 ); randomizePitch( testR, 4.0 ); }
    if( controller.hatState[0] ) { randomizeOneSize( testL, 4000.0 ); }
    else if( !controller.hatState[0] ) { randomizeOneSize( testL, 0.0 ); }
    if( controller.hatState[1] ) { randomizeOneSize( testR, 4000.0 ); }
    else if( !controller.hatState[1] ) { randomizeOneSize( testR, 0.0 ); }
    if( controller.buttonState[3] ) setPitch( testL, 1.0 );
    if( controller.buttonState[4] ) setPitch( testR, 1.0 );
     
    // size
    setSize( testL, ( Math.fabs( controller.joysticks[0] ) * 90.0 ) + 5.0 );
    setSize( testR, ( Math.fabs( controller.joysticks[3] ) * 90.0 ) + 5.0 );
    randomizeSize( testL ); randomizeSize( testR );
    10::ms => now;
}
