//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Grain.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Grain.chug Grain-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Grain.chug Grain-test.ck -v3`
//--------------------------------------------------------------------

Grain test => WvOut record => blackhole;

record.wavFilename( "GRAIN-TEST.wav" );

test.randomSize( 200.0 );
<<< test.randomSize(), test.size() >>>;

test.size( 300.0 );

for( int i; i < 25; i++ )
{
	if( i > 10 ) test.randomSize( 0.0 );
	// test.size( Math.randomf() * 45.0 + 0.001 );
	<<< test.size() >>>;
	0.5::second => now;
}

record.closeFile();