//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Sampler.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Sampler.chug Sampler-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Sampler.chug Sampler-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

// instantiate a Sampler
Sampler obj => NRev rev( 0.015 ) => Gain vol( 0.8 ) => dac;

obj.file( "../include/blackpaint.WAV" ) $ int => int size;

obj.pitch( 1.0 );
obj.position( Math.random2( 0, size ) );

size => int i;
100.0 => float runRate;

while( true ) 
{
    obj.loopLength( Math.randomf() * 0.8 );
    <<< obj.loopLength() >>>;
    2000::ms => now;
}