//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Sampler.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Sampler.chug Sampler-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Sampler.chug Sampler-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

// instantiate a Sampler
Sampler obj => NRev rev => Gain vol( 0.8 ) => dac;

obj.file( "../include/randomvaporwave.WAV" ) => float size;

float i;
100.0 => float runRate;

while( true ) 
{
    0.01 +=> i;
    if( i > 1.0 ) 1.0 -=> i;
    if( Math.randomf() < 0.1 ) obj.pitch( Math.randomf() * 2.0 );
    if( Math.randomf() < 0.05 ) { rev.mix( 0.5 ); 5000.0 => runRate; }
    else { rev.mix( 0.0012 ); 100.0 => runRate; }
    obj.position( Math.random2f( 0, i ), 1.0 );
    // <<< obj.pitch(), obj.position() >>>;
    runRate::ms => now;
}