//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Sampler.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Sampler.chug Sampler-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Sampler.chug Sampler-test.ck -v3`
//--------------------------------------------------------------------

@import "emc-ckclasses/Game-Controller.ck"

// instantiate a Sampler
Sampler obj => Gain vol( 0.8 ) => dac;
// HID input and HID message
Hid hi;
HidMsg msg;

obj.file( "../include/randomvaporwave.WAV" ) => float size;

// open joystick 0, exit on fail
if(!hi.openJoystick(0)) me.exit();
<<< "joystick '" + hi.name() + "' ready", "" >>>;

// <<< obj.pitch(), obj.position() >>>;

while( true ) 
{
    // wait on HidIn as event
    hi => now;

    // messages received
    while( hi.recv( msg ) )
    {
        // joystick axis motion
        if( msg.isAxisMotion() )
        {
            if( msg.which == 0 ) { obj.position( Math.fabs( msg.axisPosition ) ); }
            else if( msg.which == 1 ) { obj.pitch( ( msg.axisPosition * 3.0 ) + 1.0 ); }
        }
        // joystick button down
        else if( msg.isButtonDown() )
        {
            <<< "joystick button", msg.which >>>;
        }
    }
    
    1::ms => now;
}