//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Atmosphere.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Atmosphere.chug Atmosphere-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Atmosphere.chug Atmosphere-test.ck -v3`
//--------------------------------------------------------------------

// instantiate a Atmosphere
Atmosphere2 obj("yuo.wav") => WvOut record[9] => dac;

for( int i; i < record.size(); i++ ) record[i].wavFilename("test"+i+".wav");

obj.size( 43.0 );

// call obj.param() with argument of 5; same as obj.param(5)
for( int i; i < 1000; i++ )
{
    80::ms => now;
	// print
	if( i < 500 ) obj.randomSize( i / 2.0 );
	<<< obj.size() >>>;
	if( i == 500 )
	{
		obj.sync();
		obj.randomSize( 0.0 );
	}
	
}

for( int i; i < record.size(); i++ ) record[i].closeFile();


