//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Matrix.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Matrix.chug Matrix-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Matrix.chug Matrix-test.ck -v3`
//--------------------------------------------------------------------

// instantiate a Matrix
Matrix2 obj;

SinOsc osc(537.0)[2] => obj => dac;

for( int i; i < osc.size(); i++ ) osc[i].freq( Math.randomf() * 1000.0 );

0.00000000124 => float phase;

while( true )
{
	phase +=> phase;
	if( phase > 2.0 * pi ) 2.0 * pi -=> phase; 
	for( int i; i < 2; i++ ) 
	{
		for( int j; j < 2; j++ )
		{
			if( j == i ) obj.param( Math.cos( phase ), i, j );
			else obj.param( Math.randomf(), i, j );
		}
	}
	//<<< Math.cos( phase ), Math.sin( phase ) >>>;
	//<<< Math.sin( phase ), Math.cos( phase ) >>>;
	//cherr <= IO.nl();
	50::ms => now;
}
