//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Sampler", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Sampler.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Sampler-test.ck boilerplate ChucK program
//      to help test your chugin (see Sampler-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "../../include/chugin.h"
#include "../include/Sampler.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR( sampler_ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( sampler_dtor );

CK_DLL_MFUN( sampler_position );
CK_DLL_MFUN( sampler_position2 );
CK_DLL_MFUN( sampler_position3 );
CK_DLL_MFUN( sampler_pitch );
CK_DLL_MFUN( sampler_pitch2 );
CK_DLL_MFUN( sampler_pitch3 );
CK_DLL_MFUN( sampler_loopLength );
CK_DLL_MFUN( sampler_loopLength2 );
CK_DLL_MFUN( sampler_stretch );
CK_DLL_MFUN( sampler_openFile );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK( sampler_tick );

// this is a special offset reserved for chugin internal data
t_CKINT sampler_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Sampler )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Sampler )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "Sampler" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")
    QUERY->begin_class( QUERY, "Sampler", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, sampler_ctor );
    // NOTE constructors can be overloaded like any other functions,
    // each overloaded constructor begins with `QUERY->add_ctor()`
    // followed by a sequence of `QUERY->add_arg()`

    // register the destructor (probably no need to change)
    QUERY->add_dtor( QUERY, sampler_dtor );

    // for UGens only: add tick function
    // NOTE a non-UGen class should remove or comment out this next line
    QUERY->add_ugen_func( QUERY, sampler_tick, NULL, 0, 1 );
    // NOTE: if this is to be a UGen with more than 1 channel,
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    QUERY->add_mfun( QUERY, sampler_position, "float", "position" );
    QUERY->add_arg( QUERY, "float", "desination" );
    QUERY->doc_func( QUERY, "Get/set the position of the file." );

    QUERY->add_mfun( QUERY, sampler_position2, "float", "position" );
    QUERY->add_arg( QUERY, "float", "desination" );
    QUERY->add_arg( QUERY, "float", "time" );
    QUERY->doc_func( QUERY, "Get/set the position of the file with a specified interpolation time." );

    QUERY->add_mfun( QUERY, sampler_position3, "float", "position" );
    QUERY->doc_func( QUERY, "Get/set the position of the file with a specified interpolation time." );

    QUERY->add_mfun( QUERY, sampler_pitch, "float", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->doc_func( QUERY, "Get/set the pitch of the file." );

    QUERY->add_mfun( QUERY, sampler_pitch2, "float", "pitch" );
    QUERY->add_arg( QUERY, "float", "pitch" );
    QUERY->add_arg( QUERY, "float", "time" );
    QUERY->doc_func( QUERY, "Get/set the pitch of the file with a specified interpolation time." );

    QUERY->add_mfun( QUERY, sampler_pitch3, "float", "pitch" );
    QUERY->doc_func( QUERY, "Get/set the pitch of the file with a specified interpolation time." );

    QUERY->add_mfun( QUERY, sampler_loopLength, "float", "loopLength" );
    QUERY->add_arg( QUERY, "float", "length" );
    QUERY->doc_func( QUERY, "Get/set the length of the loop." );

    QUERY->add_mfun( QUERY, sampler_loopLength2, "float", "loopLength" );
    QUERY->doc_func( QUERY, "Get/set the length of the loop." );

    QUERY->add_mfun( QUERY, sampler_stretch, "int", "stretch" );
    QUERY->add_arg( QUERY, "int", "factor" );
    QUERY->doc_func( QUERY, "Insert n number of zeros between file samples." );

    QUERY->add_mfun( QUERY, sampler_openFile, "int", "file" );
    QUERY->add_arg( QUERY, "string", "file" );
    QUERY->doc_func( QUERY, "Open file to be read." );
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    sampler_data_offset = QUERY->add_mvar( QUERY, "int", "@s_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( sampler_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, sampler_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    Sampler * s_obj = new Sampler( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, sampler_data_offset ) = (t_CKINT)s_obj;
}


// implementation for the destructor
CK_DLL_DTOR( sampler_dtor )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( s_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, sampler_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICK( sampler_tick )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );
 
    // invoke our tick function; store in the magical out variable
    if( s_obj ) *out = s_obj->tick();

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN( sampler_position )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    // get next argument
    // NOTE argument type must match what is specified above in CK_DLL_QUERY
    // NOTE this advances the ARGS pointer, so save in variable for re-use
    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    
    // call setParam() and set the return value
    RETURN->v_float = s_obj->setPosition( arg1 );
}

// example implementation for setter
CK_DLL_MFUN( sampler_position2 )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    // get next argument
    // NOTE argument type must match what is specified above in CK_DLL_QUERY
    // NOTE this advances the ARGS pointer, so save in variable for re-use
    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    t_CKFLOAT arg2 = GET_NEXT_FLOAT( ARGS );
    
    // call setParam() and set the return value
    RETURN->v_float = s_obj->setPosition( arg1, arg2 );
}

// example implementation for setter
CK_DLL_MFUN( sampler_position3 )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );
    
    // call setParam() and set the return value
    RETURN->v_float = s_obj->position->getTarget();
}


// example implementation for getter
CK_DLL_MFUN( sampler_pitch )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );

    // call getParam() and set the return value
    RETURN->v_float = s_obj->setPitch( arg1 );
}

// example implementation for getter
CK_DLL_MFUN( sampler_pitch2 )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    t_CKFLOAT arg2 = GET_NEXT_FLOAT( ARGS );

    // call getParam() and set the return value
    RETURN->v_float = s_obj->setPitch( arg1, arg2 );
}

// example implementation for getter
CK_DLL_MFUN( sampler_pitch3 )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    // call getParam() and set the return value
    RETURN->v_float = s_obj->pitch->getTarget();
}

CK_DLL_MFUN( sampler_loopLength )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );
    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    // call getParam() and set the return value
    RETURN->v_float = s_obj->setLoopLength( arg1 );
}

CK_DLL_MFUN( sampler_loopLength2 )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );
    // call getParam() and set the return value
    RETURN->v_float = s_obj->loopLength;
}

CK_DLL_MFUN( sampler_stretch )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    t_CKUINT arg1 = GET_NEXT_UINT( ARGS );

    RETURN->v_int = s_obj->stretch( arg1 );
}

CK_DLL_MFUN( sampler_openFile )
{
    // get our c++ class pointer
    Sampler * s_obj = (Sampler *)OBJ_MEMBER_INT( SELF, sampler_data_offset );

    Chuck_String * path = GET_NEXT_STRING( ARGS );
    // open file
    RETURN->v_int = s_obj->openFile( API->object->str( path ) );
}